import { ChangeEvent, useEffect, useRef, useState } from "react";
import { fetchGames, Game, PROFILE_LABEL, Profile } from "./catalogue";
import { Chip8Runtime, DEFAULT_CPU_HZ, KEYMAP, MAX_CPU_HZ, MIN_CPU_HZ, RuntimeState } from "./runtime";
import "./style.css";

const DEFAULT_PALETTE = ["#02040c", "#33ffba", "#ff40be", "#ffffff", "#3180ff", "#ffbe42", "#b766ff", "#5aebff", "#ff5e5e", "#6eff70", "#ff8e3a", "#ff73e1", "#6caaFF", "#ffe65c", "#9affE1", "#e6ecff"];
const PROFILES = Object.keys(PROFILE_LABEL) as Profile[];

export default function App() {
  const runtime = useRef<Chip8Runtime | undefined>(undefined); const canvas = useRef<HTMLCanvasElement>(null);
  const [games, setGames] = useState<Game[]>([]), [filter, setFilter] = useState(""), [profileFilter, setProfileFilter] = useState<Profile | "">("");
  const [library, setLibrary] = useState(true), [status, setStatus] = useState("Chargement des bibliothèques…"), [error, setError] = useState("");
  const [state, setState] = useState<RuntimeState>(), [palette, setPalette] = useState(DEFAULT_PALETTE), [settings, setSettings] = useState(false), [debug, setDebug] = useState(false), [cpu, setCpu] = useState(DEFAULT_CPU_HZ);

  useEffect(() => { let active = true; void Chip8Runtime.create().then(value => { if (!active) return; runtime.current = value; value.subscribe(setState); value.start(); }).catch(value => setError(`Initialisation WASM impossible : ${String(value)}`)); void fetchGames().then(({ games, errors }) => { if (!active) return; setGames(games); setStatus(`${games.length} jeux disponibles`); setError(errors.join(" — ")); }); return () => { active = false; runtime.current?.stop(); }; }, []);
  useEffect(() => { const handler = (event: KeyboardEvent) => { const app = runtime.current; if (!app || library || (event.target instanceof HTMLInputElement)) return; const key = KEYMAP[event.code]; if (key !== undefined) { event.preventDefault(); app.setKey(key, event.type === "keydown", event.code); } if (event.type === "keydown") { if (event.code === "Space") { event.preventDefault(); app.togglePause(); } if (event.code === "F10") { event.preventDefault(); app.step(); } if (event.code === "F1") void app.setProfile("chip8"); if (event.code === "F2") void app.setProfile("chip48"); if (event.code === "F3") void app.setProfile("modern"); if (event.code === "F4") void app.setProfile("superchip"); if (event.code === "F6") void app.setProfile("xochip"); if (event.code === "Escape") setLibrary(true); } }; const release = () => Object.entries(KEYMAP).forEach(([, key]) => runtime.current?.setKey(key, false)); window.addEventListener("keydown", handler); window.addEventListener("keyup", handler); window.addEventListener("blur", release); return () => { window.removeEventListener("keydown", handler); window.removeEventListener("keyup", handler); window.removeEventListener("blur", release); }; }, [library]);
  useEffect(() => { if (!state || !canvas.current) return; const target = canvas.current; target.width = state.width; target.height = state.height; const context = target.getContext("2d")!; const image = context.createImageData(state.width, state.height); state.frame.forEach((color, index) => { const rgb = hex(palette[color] ?? palette[0]); image.data.set([rgb[0], rgb[1], rgb[2], 255], index * 4); }); context.putImageData(image, 0, 0); }, [state, palette]);
  const launch = async (game: Game) => { try { setStatus(`Téléchargement de ${game.name}…`); const response = await fetch(game.url); if (!response.ok) throw new Error(String(response.status)); if (game.palette) setPalette(previous => [...game.palette!, ...previous.slice(4)]); await runtime.current?.load(new Uint8Array(await response.arrayBuffer()), game.profile); await runtime.current?.resumeAudio(); setLibrary(false); setDebug(false); setStatus(`${game.name} lancé`); } catch (reason) { setError(`Impossible de charger ${game.name} : ${String(reason)}`); } };
  const local = async (event: ChangeEvent<HTMLInputElement>) => { const file = event.target.files?.[0]; if (!file) return; await runtime.current?.load(new Uint8Array(await file.arrayBuffer()), "chip8"); await runtime.current?.resumeAudio(); setLibrary(false); setDebug(false); };
  const visible = games.filter(game => (!profileFilter || game.profile === profileFilter) && `${game.name} ${game.source}`.toLowerCase().includes(filter.toLowerCase()));
  if (library) return <main className="library"><h1>Bibliothèque de jeux CHIP-8</h1><p>Choisissez une ROM déjà compilée, ou ouvrez un fichier local.</p><label className="local">Ouvrir un fichier .ch8 <input type="file" accept=".ch8,application/octet-stream" onChange={local} /></label><div className="filters"><input placeholder="Rechercher" value={filter} onChange={event => setFilter(event.target.value)} /><select value={profileFilter} onChange={event => setProfileFilter(event.target.value as Profile | "")}><option value="">Toutes les architectures</option>{PROFILES.map(profile => <option key={profile} value={profile}>{PROFILE_LABEL[profile]}</option>)}</select></div><p>{status}</p>{error && <p className="error">{error}</p>}<section className="games">{visible.map(game => <article key={`${game.source}/${game.url}`}><button onClick={() => void launch(game)}>{game.name}</button><small>Source : {game.source} · {PROFILE_LABEL[game.profile]}</small></article>)}</section></main>;
  const app = runtime.current;
  return <main><header><button onClick={() => setLibrary(true)}>Bibliothèque</button><button onClick={() => app?.togglePause()}>{app?.isPaused() ? "Reprendre" : "Pause"}</button>{debug && <button onClick={() => app?.step()}>Pas-à-pas (F10)</button>}<button onClick={() => void app?.restart()}>Redémarrer</button><button onClick={() => setSettings(true)}>Paramètres…</button><button onClick={() => { app?.enableDebug(); setDebug(true); }}>Activer le mode debug</button></header><section className={debug ? "debug-layout" : "screen"}><canvas ref={canvas} /><aside>{debug && <Debug state={state} runtime={app} onProfile={profile => void app?.setProfile(profile)} />}</aside></section>{settings && <Settings cpu={cpu} palette={palette} onClose={() => setSettings(false)} onCpu={value => { setCpu(value); app?.setCpuHz(value); }} onPalette={setPalette} />}</main>;
}
function Debug({ state, runtime, onProfile }: { state?: RuntimeState; runtime?: Chip8Runtime; onProfile: (value: Profile) => void }) { return <div className="debug"><h2>Performance</h2><p>État : {runtime?.isPaused() ? "en pause" : "exécution"}</p><p>Dernière touche : {state?.lastKey ?? "—"}</p><button onClick={() => runtime?.clearBreakpoints()}>Effacer les breakpoints</button><h2>Instructions exécutées</h2><table><thead><tr><th>BP</th><th>PC</th><th>Opcode</th><th>Instruction</th><th>Analyse</th></tr></thead><tbody>{state?.trace.slice().reverse().map(entry => <tr key={`${entry.pc}-${entry.analysis}`}><td><input type="checkbox" onChange={() => runtime?.toggleBreakpoint(entry.pc)} /></td><td>{entry.pc.toString(16)}</td><td>{entry.opcode.toString(16)}</td><td>{entry.mnemonic}</td><td>{entry.analysis.toFixed(2)} ms</td></tr>)}</tbody></table><h2>Profil</h2>{PROFILES.map(profile => <button key={profile} onClick={() => onProfile(profile)}>{PROFILE_LABEL[profile]}</button>)}</div>; }
function Settings({ cpu, palette, onClose, onCpu, onPalette }: { cpu: number; palette: string[]; onClose: () => void; onCpu: (value: number) => void; onPalette: (value: string[]) => void }) { return <div className="modal"><section><button onClick={onClose}>Fermer</button><h2>Paramètres</h2><label>Fréquence CPU <input type="number" min={MIN_CPU_HZ} max={MAX_CPU_HZ} value={cpu} onChange={event => onCpu(Number(event.target.value))} /> cycles/s</label><p>Mémoire allouée : 4 Kio (4096 octets)</p><h3>Palette</h3>{palette.map((color, index) => <label key={index}>Couleur {index} <input type="color" value={color} onChange={event => onPalette(palette.map((item, i) => i === index ? event.target.value : item))} /></label>)}</section></div>; }
function hex(value: string): [number, number, number] { const text = value.slice(1); return [parseInt(text.slice(0, 2), 16), parseInt(text.slice(2, 4), 16), parseInt(text.slice(4, 6), 16)]; }
